n1awifi: increase recovery partition size again due to LineageOS 21 code getting fatter.
During 21 compilation, we get

error: out/target/product/n1awifi/recovery.img too large (12486672 > 12485760)

Let's increase it again.  We'll never use recovery.img away.  We use
TWRP.